### PR TITLE
Feature/04

### PR DESCRIPTION
**Pull request by TaylorFoster90**

### CODE REVIEW

**Comment by jgarcia99** [comment]
:+1:

**Comment by eklemen** [comment]
:+1:  Saw your site in person today, everything looked good. Good job sir.

**Comment by jaredstevick** [comment]
:+1:  nice work man.  i especially enjoyed the ipsum

**Comment by jrutishauser** [comment]
:+1:

**Comment by al-the-x** [comment]
So this is what happens when I don't give you Emoji?

**Comment by al-the-x** [comment]
Your HTML and CSS should be in a folder called `pub/` not `initializer/`… I can see what you did there, but please correct this.

**Comment by al-the-x** [comment]
Also, there are lots of your peers who are less than halfway through. Be proactive in helping them get across the finish line as well.

**Comment by TaylorFoster90** [comment]
@al-the-x got it

**Comment by TaylorFoster90** [comment]
WIP issue 
https://github.com/TheIronYard--Orlando/FEE--2015--SPRING/issues/62#issuecomment-69592724

**Comment by al-the-x** [comment]
Great effort, Taylor. You nailed the main layout, and I love that you're playing with the code and owning it. That "Related Posts" section needs some love still. Here are some notes on the deviations you've made from the design spec FYI:
- light-colored text on a white background is hard to read
- the left border and indentation you've applied to the article titles makes them look like pull quotes
- the blues you've used for the search form make that harder to distinguish from the background

Again, great effort and keep owning the assignments... but maybe tone back the owning just a little. Experiment, sure, but the goal was as pixel-perfect to the design spec as possible with lattitude for body copy and placeholder images. Keep killing it.

**Pull request merged**
